# Generated by Django 4.2.7 on 2023-12-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.marca'),
        ),
    ]
