# Generated by Django 4.2.7 on 2023-12-04 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_evento_tipo_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('lanzamiento', 'Nuevo Lanzamiento'), ('fiesta', 'Fiesta'), ('apertura_tienda', 'Apertura de Tienda'), ('descuentos', 'Descuentos Especiales')], max_length=100),
        ),
    ]
